@echo off
set "SRC=C:\Users\wanad\.gemini\antigravity\brain\bc9dd4e7-e072-4c54-ba66-badb01dcc09d\fianar_tsara_guest_house_1765454555912.png"
set "DST=c:\Users\wanad\OneDrive\Documents\Projets_Git\guide-complet-Madagascar-du-Nord\images\toliara"

if not exist "%DST%" mkdir "%DST%"

copy "%SRC%" "%DST%\toliara_arboretum.png"
copy "%SRC%" "%DST%\toliara_saint_augustin.png"
copy "%SRC%" "%DST%\toliara_anakao.png"
copy "%SRC%" "%DST%\toliara_baobabs_mangily.png"
copy "%SRC%" "%DST%\toliara_musee_mer.png"
copy "%SRC%" "%DST%\toliara_giancarlo.png"
copy "%SRC%" "%DST%\toliara_chez_freddy.png"
copy "%SRC%" "%DST%\toliara_etoile_mer.png"
copy "%SRC%" "%DST%\toliara_table_alexandre.png"
copy "%SRC%" "%DST%\toliara_vezo_anakao.png"
copy "%SRC%" "%DST%\toliara_bakouba.png"
copy "%SRC%" "%DST%\toliara_moringa.png"
copy "%SRC%" "%DST%\toliara_peter_pan.png"
copy "%SRC%" "%DST%\toliara_paradisier.png"
copy "%SRC%" "%DST%\toliara_dunes_ifaty.png"
copy "%SRC%" "%DST%\toliara_thotre_chose.png"
copy "%SRC%" "%DST%\toliara_plazza.png"
copy "%SRC%" "%DST%\toliara_zaza_club.png"
copy "%SRC%" "%DST%\toliara_chez_alain.png"
copy "%SRC%" "%DST%\toliara_mangily_bar.png"
echo Done.
